improve: propagation checks
Make the propagation checks resilient to flaky convergence between both
front-end authoritative servers, and back-end anycast PoPs.

There is an overall timeout (optionally configurable via argument,
defaults to 20 minutes). Inside that window the algorithm considers a
green (positive convergence test) when all authoritative servers return
the challenge token.

However, to avoid the chance of flaky answers when the backend PoPs
converge (which would leave open the chance for DNS01 to fail after we
return success), instead of returning immediately we begin a
"stabilization phase" after the first green.

The stabilization phase continues to attempt getting green tests until a
secondary stable_threshold limit is reached. This secondary limit is
initially adjusted to penalize longer times for a first green test.

Ultimately, the algorithm is however lenient: if stabilization isn't
achieved, it will still succeed upon reaching the overall timeout.

Options for different behaviors that can be added later:

- default to strict instead of lenient stabilization (fail on timeout)
- reset first_green whenever a subsequent test fails (also stricter)

The idea is to succeed more quickly when convergence appears to occur
smoothly, and be increasingly stricter with less smooth convergences.

A scalable/top-limited backoff time is applied between checks.

diff --git a/dns01 b/dns01
--- a/dns01
+++ b/dns01
@@ -27,21 +27,61 @@ parse_domain() {
 }
 
 wait_propagation() {
-  local record="$1" expect="\"$2\"" timeout=${3:-600} backoff=2 ns nameservers=("8.8.8.8" "1.1.1.1")
+  local name="$1" zone="$2" token="$3"
+  local timeout=${4:-1200} backoff=1 max_backoff=45 start=$(date +%s)
+  local now=$start first_green=0 stabilizing=0 stable_threshold=0
+  local n nameservers=() test_nameservers=()
 
-  # readarray -t nameservers -O ${#nameservers[@]}< <(dig +short NS "${record#*_acme-challenge.}" @8.8.8.8)
+  readarray -t nameservers< <(dig +short NS "$zone" @8.8.8.8)
+  (( ${#nameservers[@]} )) || {
+    log "Couldn't find authoritative nameservers for zone $zone - aborting"
+    return 1
+  }
+  test_nameservers=( "${nameservers[@]}" )
 
-  log "Waiting for TXT propagation ($record)"
-  while (( (timeout -= (backoff *= 2)) > 0 )); do
-    for ns in "${nameservers[@]}"; do
-      dig +short TXT "$record" @"$ns" | grep -Fxq "$expect" && { log "Propagated in ${backoff}s via $ns"; exit 0; }
+  log "Waiting for TXT propagation ($name.$zone)"
+  while (( now - start < timeout )); do
+    for (( n = ${#test_nameservers[@]}; n--; )); do
+      dig +short TXT "$name.$zone" @"${test_nameservers[$n]}" | grep -Fq "$token" && unset test_nameservers[$n]
     done
-    sleep "$backoff"
-    printf '.' >&2
+
+    now=$(date +%s) test_nameservers=( "${test_nameservers[@]}" )
+    (( ${#test_nameservers[@]} )) || {
+      if (( ! stabilizing )); then
+        stabilizing=$now
+
+        # decide how long we're going to test to assume a "stable" data plane
+        # depending on how long it took us to this first positive test
+        # longer first-positives are "penalized" and less trusted, so they get
+        # longer stable_threshold values
+
+        # note that the default is "lenient", ie we still will give up and green
+        # light the whole propagation if we reach $timeout before
+        # stable_threshold
+
+        (( first_green = now - start ))
+        if (( first_green < 10 )); then stable_threshold=10
+        elif (( first_green < 30 )); then stable_threshold=30
+        elif (( first_green < 60 )); then stable_threshold=60
+        elif (( first_green < 120 )); then stable_threshold=120
+        elif (( first_green < 240 )); then stable_threshold=240
+        else (( stable_threshold = (timeout - first_green < 10) ? 1 : timeout - first_green ))
+        fi
+
+      elif (( now - stabilizing >= stable_threshold )); then
+        log "Token propagated in $((now - start))s to all authoritative nameservers"
+        return 0
+      fi
+      test_nameservers=( "${nameservers[@]}" )
+    }
+
+    (( backoff = (backoff * 2 >= max_backoff ? max_backoff : backoff * 2) ))
+    printf '%s ' $backoff >&2
+    sleep $backoff
   done
   echo >&2
 
-  log "Timeout after ${backoff}s waiting for DNS propagation"
+  log "Timeout after $((now - start))s waiting for DNS propagation"
   return 1
 }
 
