refactor(dns01): rest client alias
Move the calls using conf[rest_client] to a "rest" alias defined once

diff --git a/dns01/dns01 b/dns01/dns01
--- a/dns01/dns01
+++ b/dns01/dns01
@@ -23,6 +23,8 @@ conf[dns01_streak_mod]=4
 
 source "${script[dir]}/common"
 
+alias rest="${conf[rest_client]}"
+
 parse_domain() {
   local domain="$1" wildcard=false fq zone host
   [[ $domain =~ ^(\*\.|)(([^.]+\.)*)([^.]+\.[^.]+)$ ]] && {
@@ -140,12 +142,12 @@ challenge() {
   read -r wildcard fq zone host< <(parse_domain "$domain") || err "Invalid domain syntax: $domain"
 
   local id
-  id=$("${conf[rest_client]}" getj "dns/zones/$zone" | jq -c '.data.id') || return $?
+  id=$(rest getj "dns/zones/$zone" | jq -c '.data.id') || return $?
   local name="_acme-challenge${host:+.$host}"
 
   case $mode in
     add|present)
-      "${conf[rest_client]}" put dns/zones/"$zone" id="$id" name="$name" \
+      rest put dns/zones/"$zone" id="$id" name="$name" \
         records.add="[{
           \"name\" : \"$name\",
           \"type\" : \"TXT\",
@@ -158,7 +160,7 @@ challenge() {
     del|cleanup)
       local quoted=$(printf '%s' "$token" | jq -R '@json')
 
-      "${conf[rest_client]}" put dns/zones/"$zone" id="$id" \
+      rest put dns/zones/"$zone" id="$id" \
         records.remove="[{
           \"name\" : \"$name\",
           \"type\" : \"TXT\",
@@ -255,7 +257,7 @@ go() {
   local wildcard fq zone host
   read -r wildcard fq zone host< <(parse_domain "$domain") || err "Invalid domain syntax: $domain"
 
-  "${conf[rest_client]}" get "dns/zones/$zone" &> /dev/null || err "Zone $zone is not hosted at Openprovider - aborting"
+  rest get "dns/zones/$zone" &> /dev/null || err "Zone $zone is not hosted at Openprovider - aborting"
 
   $create && \
     if $wildcard; then msg "Wilcard domain specified - ignoring --create ..."
@@ -266,7 +268,7 @@ go() {
       for address in "${addresses[@]}"; do
         [[ $address == *:* ]] && record_type=AAAA || record_type=A
 
-        "${conf[rest_client]}" getj "dns/zones/$zone" with_records=true \
+        rest getj "dns/zones/$zone" with_records=true \
           | jq -e --arg n "$fq" --arg t "$record_type" --arg a "$address" \
           '.data.records[] | select(.name==$n and .type==$t and .value==$a)' &> /dev/null && {
             msg "$fq $record_type $address already exists – skipping"
@@ -275,9 +277,9 @@ go() {
 
         msg "Creating record $fq type $record_type with address $address..."
 
-        id=${id:=$("${conf[rest_client]}" getj "dns/zones/$zone" | jq -c '.data.id')} || return $?
+        id=${id:=$(rest getj "dns/zones/$zone" | jq -c '.data.id')} || return $?
 
-        "${conf[rest_client]}" put "dns/zones/$zone" name="$zone" id="$id" \
+        rest put "dns/zones/$zone" name="$zone" id="$id" \
           records.add="[{
             \"name\":\"$host\",
             \"type\":\"$record_type\",
